export interface IpdmsService {
  getEventTypeOptions(params:any, transaction?:any): Promise<any>
  donghuanShowPdms(params:any, transaction?:any): Promise<any>
  updateAllMessageReadFlag(params:any, transaction?:any): Promise<any>
  agencyDelete(params:any, transaction?:any): Promise<any>
  messageDelete(params:any, transaction?:any): Promise<any>
  synchTreeData(params:any, transaction?:any): Promise<any>
  getAiEventTypeName(params:any, transaction?:any): Promise<any>
  getRegionEduRegionType(params:any, transaction?:any): Promise<any>
  treePath(params:string, transaction?:any): Promise<any>
  treeOrgPath(params:any, transaction?:any): Promise<any>
  synchTreeDataById(params:any, transaction?:any): Promise<any>
  getUsersByUserIds(userIds:any, transaction?:any): Promise<any>
  getUsersByPersonIds(personIds:any, transaction?:any): Promise<any>
  getUserListByOrgId(params:any, transaction?:any): Promise<any>
  getUserRolesListByUserName(userName:any, transaction?:any): Promise<any>
  getUserListByPersonIds(personIdList:any, transaction?:any): Promise<any>
  getPersonListByRoleIdNoUserId(roleId:any, transaction?:any): Promise<any>
  getPersonListByRoleId(roleId:any, transaction?:any): Promise<any>
  getUserInfoList(userIds:any, transaction?:any): Promise<any>
  getAllRoles(params:any, transaction?:any): Promise<any>
  getPersonListByPersonIds(params:any, transaction?:any): Promise<any>
  getPersonsByPersonIds(params:any, transaction?:any): Promise<any>
  patrolObjPdmsAdd(params:any, transaction?:any): Promise<any>
  patrolObjPdmsCumAdd(dataParams:any,pdmsStr:any, transaction?:any): Promise<any>
  patrolObjPdmsDel(params:any, transaction?:any): Promise<any>
  patrolObjPdmsUpdate(params:any, transaction?:any): Promise<any>
  patrolObjPdmsUpdateAll(params:any, str:any, transaction?:any): Promise<any>
  asyncRegionTree(params:any, transaction?:any): Promise<any>
  visibleCommunityList(params:any, transaction?:any): Promise<any>
  getCommunityRegionByUserName(indexCode:any,userId:any,regionData:any, transaction?:any): Promise<any>
  asyncRegionTreeSearch(params:any, transaction?:any): Promise<any>
  asyncOrgTree(params:any, transaction?:any): Promise<any>
  asyncOrgTreeSearch(params:any, transaction?:any): Promise<any>
  getAllRegionByUserName(params:any, transaction?:any): Promise<any>
  getRegionByUserName(params:any, transaction?:any): Promise<any>
  getRegionLimitBySearchName(params:any, transaction?:any): Promise<any>
  getOrgByUserName(params:any, transaction?:any): Promise<any>
  getOrgLimitBySearchName(params:any, transaction?:any): Promise<any>
  asyncTreeByLimit( transaction?:any): Promise<any>
  asyncTreeByLimitByAPP(userId:any, transaction?:any): Promise<any>
  asyncTreeSearchByLimit( transaction?:any): Promise<any>
  asyncOrgTreeByLimitByApp(params:any,userId:any, transaction?:any): Promise<any>
  asyncOrgTreeByLimit( transaction?:any): Promise<any>
  asyncOrgTreeSearchByLimit( transaction?:any): Promise<any>
  regionMultiverify(params:any, transaction?:any): Promise<any>
  treePathAndEegionType(params:any,regionId:any, transaction?:any): Promise<any>
  getRegionInfo(params:any, transaction?:any): Promise<any>
}